[package]
name = "javaws_win"
version = "0.1.0"
authors = ["akashche <akashche@redhat.com>"]

[dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"
advapi32-sys = "0.2.0"
kernel32-sys = "0.2.2"
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
comctl32-sys = "0.2.0"
libc = "0.2.24"
scopeguard = "0.3.2"

